# Generated by Django 5.0.1 on 2024-02-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0002_comments_friendships_grouptbl_likes_messages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
