# Generated by Django 5.0.1 on 2024-02-09 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0003_alter_users_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='website',
        ),
    ]
