# Generated by Django 5.0.1 on 2024-02-14 08:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0004_remove_profiles_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='post_title',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
