# Generated by Django 5.0.1 on 2024-02-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0005_posts_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_title',
            field=models.TextField(),
        ),
    ]
