# Generated by Django 5.0.1 on 2024-02-16 06:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0006_alter_posts_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='user_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_title',
            field=models.TextField(max_length=255),
        ),
    ]
