# Generated by Django 5.0.2 on 2024-02-19 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0007_posts_user_name_alter_posts_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='media_url',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
