# Generated by Django 5.0.1 on 2024-02-19 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0008_alter_posts_media_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='cover_photo_url',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='profile_picture_url',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
