# Generated by Django 5.0.1 on 2024-02-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0010_remove_likes_user_id_likes_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='no_of_followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profiles',
            name='no_of_following',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profiles',
            name='no_of_posts',
            field=models.IntegerField(default=0),
        ),
    ]
