# Generated by Django 5.0.1 on 2024-02-27 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0011_profiles_no_of_followers_profiles_no_of_following_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friendships',
        ),
    ]
