# Generated by Django 5.0.1 on 2024-03-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0015_posts_profile_picture_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='profile_picture_url',
        ),
        migrations.AddField(
            model_name='posts',
            name='profile_picture_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
