# Generated by Django 5.0.1 on 2024-03-02 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0016_remove_posts_profile_picture_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='profile_picture_path',
            new_name='profile_picture_url',
        ),
    ]
