# Generated by Django 5.0.1 on 2024-03-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0017_rename_profile_picture_path_posts_profile_picture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='report_count',
            field=models.IntegerField(default=0),
        ),
    ]
