# Generated by Django 5.0.1 on 2024-03-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0018_posts_report_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_id', models.IntegerField()),
                ('username', models.CharField(max_length=250)),
                ('report_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
